 'use strict';
const clips=[{src:'videos/clip-1.mp4',answer:'real'},{src:'videos/clip-2.mp4',answer:'manipulated'},{src:'videos/clip-3.mp4',answer:'real'},{src:'videos/clip-4.mp4',answer:'manipulated'},{src:'videos/clip-5.mp4',answer:'real'}];
const $=id=>document.getElementById(id);const label=x=>x==='real'?'Authentic':'AI-manipulated';let current=0;let responses=[];
function focusHeading(id){$(id).focus();$(id).scrollIntoView({behavior:'smooth',block:'start'});}
function render(){ $('form').reset();$('form').hidden=false;$('reveal').hidden=true;$('media-error').hidden=true;$('confidence-value').textContent='75%';$('stage').textContent=current<2?'ROUND 1 / FIRST IMPRESSIONS':current<4?'ROUND 2 / TEST YOUR REASONING':'ROUND 3 / A FRESH CHALLENGE';$('heading').textContent='Clip '+(current+1)+' of '+clips.length;$('progress').value=current;$('round-note').textContent=current<2?'Notice what makes a clip feel convincing.':current<4?'Bring your reflection into the next judgment. You do not have to be certain.':'Use what you have learned on one fresh clip.';$('video').src=clips[current].src;$('video').load();focusHeading('heading');}
$('start').onclick=()=>{$('intro').hidden=true;$('activity').hidden=false;render();};
$('confidence').oninput=()=>{$('confidence-value').textContent=$('confidence').value+'%';};
$('video').onerror=()=>{$('media-error').hidden=false;};
$('form').onsubmit=e=>{e.preventDefault();const judgment=new FormData(e.target).get('judgment');if(!judgment||!$('reason').value.trim()){ $('reason').setCustomValidity('Write a short reason before continuing.');$('reason').reportValidity();return; }const confidence=Number($('confidence').value);const correct=judgment===clips[current].answer;responses.push({judgment,confidence,reason:$('reason').value.trim(),correct,reflection:''});$('video').pause();$('form').hidden=true;$('reveal').hidden=false;$('outcome').textContent=correct?'Your judgment matched the answer.':'A useful surprise: your judgment differed.';$('explanation').textContent='The supplied answer key identifies this clip as '+label(clips[current].answer).toLowerCase()+'. Authentic footage can still contain fictional scenes, misleading captions, edits, or untrue claims.';$('calibration').textContent=correct?'You chose '+confidence+'% confidence. Which part of your reasoning would still help on a different clip?':'You chose '+confidence+'% confidence. What made you certain, and what evidence was missing? An incorrect judgment does not mean every clip should be distrusted.';$('reflection').value='';$('next').textContent=current===4?'Try the sharing mission →':'Next clip →';$('reveal').scrollIntoView({behavior:'smooth'});};
$('reason').oninput=()=>{$('reason').setCustomValidity('');};
$('next').onclick=()=>{responses[current].reflection=$('reflection').value;current++;if(current<clips.length)render();else{$('video').pause();$('activity').hidden=true;$('decision').hidden=false;document.querySelector('#decision h2').focus();$('decision').scrollIntoView();}};
$('decision-form').onsubmit=e=>{e.preventDefault();const action=new FormData(e.target).get('action');$('decision-form').hidden=true;$('decision-feedback').hidden=false;$('decision-title').textContent=action==='check'?'Good choice: verify before acting.':'Try an evidence-based next step.';};
$('show-map').onclick=()=>{$('learning-check').hidden=true;$('decision').hidden=true;$('results').hidden=false;const correct=responses.filter(r=>r.correct).length;const high=responses.filter(r=>!r.correct&&r.confidence>=80).length;$('summary').textContent=correct+' of 5 judgments matched the supplied key. '+high+' incorrect judgment'+(high===1?' was':'s were')+' made with at least 80% confidence.';$('rows').replaceChildren();responses.forEach((r,i)=>{const tr=document.createElement('tr');[String(i+1),label(r.judgment),r.confidence+'%',label(clips[i].answer),r.correct?'Matched':'Differed'].forEach(t=>{const td=document.createElement('td');td.textContent=t;tr.append(td);});$('rows').append(tr);});focusHeading('results-heading');};
$('print').onclick=()=>window.print();$('restart').onclick=()=>{current=0;responses=[];$('results').hidden=true;$('decision').hidden=true;$('decision-form').hidden=false;$('decision-feedback').hidden=true;$('takeaway').value='';$('activity').hidden=false;render();};

$('finish').onclick=()=>{$('decision').hidden=true;$('learning-check').hidden=false;focusHeading('check-heading');};
$('check-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);const key=['a','b','b'];const feedback=['Confidence describes certainty; correctness describes whether a judgment matches the answer. A confident error is a reason to examine your reasoning, not distrust everything.','Authentic footage can carry a false or misleading claim. Check the caption, date, and full context separately.','Trace the original source, inspect its context, and compare reliable independent sources. If evidence is insufficient, pause before sharing.'];let score=0;$('check-explanations').replaceChildren();key.forEach((answer,i)=>{const right=data.get('q'+(i+1))===answer;if(right)score++;const p=document.createElement('p');p.textContent=(i+1)+'. '+(right?'You got it. ':'Revisit this idea. ')+feedback[i];$('check-explanations').append(p);});$('check-score').textContent=score+' of 3 ideas applied correctly.';$('check-form').hidden=true;$('check-feedback').hidden=false;$('check-feedback').scrollIntoView({behavior:'smooth'});};
$('retry-check').onclick=()=>{$('check-form').reset();$('check-form').hidden=false;$('check-feedback').hidden=true;focusHeading('check-heading');};
const restartActivity=$('restart').onclick;$('restart').onclick=()=>{restartActivity();$('learning-check').hidden=true;$('check-form').reset();$('check-form').hidden=false;$('check-feedback').hidden=true;};
