(function(root){
'use strict';
const questions=[
 {prompt:'1. A student was 95% confident that the shuttle had closed. Record F contradicts that claim. What follows?',options:[['a','Reduce confidence in every future clip by the same amount.'],['b','Examine this reasoning: confidence described certainty, not whether the closure claim was correct.'],['c','Treat the original uploader as the stronger source because the clip was vivid.']],key:'b',feedback:'Confidence and correctness are different. The current operator notice contradicts permanent closure. This error is a reason to revisit the evidence, not apply blanket distrust.'},
 {prompt:'2. Which conclusion separates the recording from its caption?',options:[['a','The current notice establishes that this video was AI-generated.'],['b','Because the caption is wrong, the clip cannot contain camera footage.'],['c','The permanent-closure claim is contradicted; the recording’s authenticity remains unresolved.']],key:'c',feedback:'Record F addresses shuttle service. Record G leaves video provenance unresolved. Evidence against a caption does not establish whether AI altered a recording.'},
 {prompt:'3. What is the strongest next step before sharing?',options:[['a','Use the current operator notice to correct the closure claim; seek the original recording before making an authenticity claim.'],['b','Count the two reposts as corroboration and share with a question mark.'],['c','Seek a third account repeating the same uploader before deciding.']],key:'a',feedback:'Records D and E are repeated claims from one source, not independent confirmation. Record F addresses current service; finding the original would help answer the separate authenticity question.'}
];
const clips=[
 {id:1,title:'First impression / public speech',description:'A woman stands behind a lectern with microphones in a large room. She speaks and moves her face and head. A USA TODAY mark is visible. No original source link, date, or alteration record accompanies this excerpt.',prompt:'What makes a clip feel convincing? Watch the silent excerpt or use the text observation.',reason:'Name one detail that influenced you—and one thing the excerpt cannot establish.',feedback:'A public-speaking setting and a news mark can create familiarity. A visible logo is a clue to investigate, not proof of origin. An original publication and alteration record would be more useful than appearance alone.'},
 {id:2,title:'Second impression / interview',description:'A man holds a microphone on a stage and moves his mouth while speaking. Event branding appears on the microphone and in the picture. The excerpt does not provide an original source link, a date, or an alteration history.',prompt:'Try a different question: what evidence is missing? Use the silent excerpt or the text observation.',reason:'What source or context would you look for before trusting a claim attached to this clip?',feedback:'A recognizable person and event branding can make an interview feel familiar. They do not establish whether the voice or face was altered. Compare the excerpt with the original full recording and its context.'},
 {id:3,title:'News-style presentation',description:'A news-style screen shows water covering a street beside houses and vehicles. The recording is shown within a broadcast graphic. A short excerpt and news-style framing do not establish the original date, location, or alteration history.',feedback:'Trace the broadcast and full context before accepting a new caption.'},
 {id:4,title:'Edited reaction scene',description:'A young man sits near a screen displaying “The Bunny Garden.” Cartoon eyes are overlaid on his face. Other graphics appear in this edited scene. The presence of overlays does not establish which, if any, elements were altered by AI.',feedback:'Ordinary graphics, filters, and AI alteration are different things. An editing history is needed to distinguish them.'},
 {id:5,title:'Product advertisement',description:'A woman appears in a commercial-style scene. The excerpt ends with a group of Smartwater bottles and advertising text. Polished advertising, acting, and product graphics do not establish AI alteration or the truth of a product claim.',feedback:'A commercial can be recorded footage and still use acting or persuasive claims. Check production provenance and claim evidence separately.'}
];
function gradeCheck(answers){const results=questions.map((q,i)=>({correct:answers[i]===q.key,feedback:q.feedback}));return {score:results.filter(r=>r.correct).length,total:questions.length,results};}
function gradeContext(answer,action){return {conclusion:answer==='a',action:action==='hold',correct:answer==='a'&&action==='hold'};}
function validConfidence(value){return value!==''&&value!==null&&Number.isFinite(Number(value))&&Number(value)>=50&&Number(value)<=100&&Number.isInteger(Number(value));}
const api={questions,clips,gradeCheck,gradeContext,validConfidence};
if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.SIB=api;
})(typeof window!=='undefined'?window:globalThis);
